# Generated by Django 5.1.6 on 2025-02-24 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default='null', max_length=50),
        ),
        migrations.AddField(
            model_name='car',
            name='vin',
            field=models.CharField(default='null', max_length=17, unique=True),
        ),
    ]
